config/routes.rb
Auction::Application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  root :to => "lots#index"
  get 'admin' => 'admin/categories#index'

  namespace :admin do
    resources :products, :categories, :lots
  end

  resources :lots, only: [:index, :show] do
    resources :bets, only: [:create]
  end

end

app/models/lot.rb
class Lot < ActiveRecord::Base

  belongs_to :product
  has_many :bets
  validates :product_id, :time_step, :bet_step, presence: true
  validates :time_step, numericality: { greater_than_or_equal_to: 30 }

  enum :status, [:not_started, :started, :finished], :allow_nil => true
  after_create :init_lot

  def name
    self.product.name
  end

  def description
    self.product.description
  end

  def category
    self.product.category
  end

  def pictures
    self.product.pictures
  end

  def active?
    if self.status == :started
      true
    else
      false
    end
  end

  def change_for_bet
    self.time_end += self.time_step
    self.current_price += self.bet_step
    self.save!
  end

  def last_bet_user
    if self.bets.count > 0 && self.bets.last.user_id
      User.find(self.bets.last.user_id)
    else
      nil
    end
  end

  private
    def init_time_start
      self.time_start = Time.now
    end

    def init_time_end
      self.time_end = self.time_start + self.time_step
    end

    def init_current_price
      self.current_price = self.start_price
    end

    def init_status
      self.status = :not_started
    end

    def init_lot
      init_time_start
      init_time_end
      init_current_price
      init_status
      self.save!
    end

end

app/controllers/admin/lots_controller.rb
class Admin::LotsController < Admin::BaseController
  before_action :set_lot, only: [:show, :edit, :update, :destroy]
  before_action :set_time_start, only: [:update] # temp

  def index
    @lots = Lot.all
  end

  def show
  end

  def new
    @lot = Lot.new
    @products = Product.all.map {|p| [p.name, p.id]}
  end

  def create
    @lot = Lot.new(lot_params)
    if @lot.save
      flash[:success] = "Lot created."
      redirect_to [:admin, @lot]
    else
      render 'new'
    end
  end

  def edit
    @products = Product.all.map {|p| [p.name, p.id]}
  end

  def update
    if @lot.update_attributes(lot_params)
      if is_starting? # temp
        @lot.time_end = @lot.time_start + @lot.time_step
        @lot.save
      end
      flash[:success] = "Lot updated."
      redirect_to [:admin, @lot]
    else
      render 'edit'
    end
  end

  def destroy
    @lot.destroy
    flash[:success] = "Lot deleted."
    redirect_to admin_lots_url
  end

  private
    def lot_params
      params.require(:lot).permit(:product_id, :time_step, :bet_step, :start_price, :status)
    end

    def set_lot
      @lot = Lot.find(params[:id])
    end

    def is_starting? #I don't like this idea
      prev_status = @lot.status
      current_status = params[:lot][:status]
      starting =  prev_status.to_s == 'not_started' && current_status == 'started'
      if starting
        return true
      else
        return false
      end
    end

    def set_time_start # temp
      @lot.time_start = Time.now if is_starting?
    end
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController
  
  def index
   @lots= Lot.order('created_at DESC').page(params[:page])

  end

  def show
    @lot = Lot.find(params[:id])
  end

end

app/helpers/admin/lots_helper.rb
module Admin::LotsHelper
end

app/helpers/lots_helper.rb
module LotsHelper
end

app/views/admin/lots/_error_messages.html.slim
-if @lot.errors.any?
    div id="error_explanation"
      div class="alert alert-error"
        |The form contains #{pluralize(@lot.errors.count, "error")}.
      ul
        - @lot.errors.full_messages.each do |msg|
            li = "*#{msg}"

app/views/admin/lots/_form.html.slim
div.row
  .col-lg-7
    .panel.panel-default
      .panel-heading
        .category_title
          - if @lot.new_record?
            | Create new lot
          - else
            = "Edit "+@lot.name
      .panel-body
        = form_for [:admin, @lot] do |f|
          .form-group
            = render 'error_messages'
          .form-group
            = f.label :product_id
            = f.select :product_id, Product.all.map {|p| [p.name, p.id]}, {include_blank: 'None'}, class: 'form-control'
          .form-group
            = f.label :start_price
            = f.text_field :start_price, class: 'form-control'
          .form-group
            = f.label :time_step
            = f.text_field :time_step, class: 'form-control'
          .form-group
            = f.label :time_end
            = f.text_field :time_end, class: 'form-control', readonly: true
          .form-group
            = f.label :status
            = f.text_field :status, class: 'form-control', readonly: true
          .form-group
            = f.label :bet_step
            = f.text_field :bet_step, class: 'form-control'

          .form-group
            - if @lot.new_record?
              = f.submit "Create the lot", class: "btn btn-large btn-primary"
            - else
              = f.submit "Edit the lot", class: "btn btn-large btn-primary"
              | &nbsp
              = link_to "Show", admin_lot_path(@lot), class: 'btn btn-primary'
            - if @lot.status.to_s == 'not_started'
              | &nbsp
              = link_to 'Activate', '#', class:'lot_activate_link btn btn-success'
            - if @lot.status.to_s == 'started'
              | &nbsp
              = link_to 'Reset', '#', class:'lot_reset_link btn btn-primary'

app/views/admin/lots/_list.html.slim
.row
  .col-lg-12
    .panel.panel-default
      .panel-heading
        - if defined?(title_list)
          = title_list
      .panel-body
        .table-responsive
          table#dataTables.table.table-striped.table-bordered.table-hover
            thead
              tr
                th Id
                th Name
                th Category
                th Min bet
                th
                th
            tbody
              - for l in @lots
                tr
                  td
                    = l.id
                  td
                    = link_to l.name, admin_lot_path(l), class: 'lot'
                  td
                    = l.category.name
                  td.center
                    = link_to "Edit", edit_admin_lot_path(l)
                  td.center
                    = link_to "Delete", admin_lot_path(l), method: "delete", data: { confirm: "You sure?" }, class: 'delete_link'

app/views/admin/lots/_right.html.slim
.col-lg-4
  .well.sidebar-nav
    p
      = link_to "Add Lot", new_admin_lot_path, class: "btn btn-small btn-primary"

    ul.nav.nav-list
      li.nav-header

    /= render 'jstree'
/.span3
  .well.sidebar-nav
    p
      = link_to "Add Lot", new_admin_lot_path, class: "btn btn-small btn-primary"
    ul.nav.nav-list
      li.nav-header
      li= link_to "Link 1", "/path1"

app/views/admin/lots/index.html.slim
= render 'list', title_list: 'Lots'

app/views/admin/lots/show.html.slim
.row
  .col-lg-5
    .panel.panel-default
      .panel-heading
        .lot_title
          = @lot.name
      .panel-body
        p
          |Category = #{@lot.category.name}
        p
          |Time step = #{@lot.time_step}
        p
          |Start price = #{@lot.start_price}
        p
          |Status = #{@lot.status}
        p
          |Bet step = #{@lot.bet_step}
        p
          |Time start = #{@lot.time_start.to_s}
        p
          |Time end = #{@lot.time_end}
        p
          - if @lot.pictures
            - @lot.pictures.each do |p|
                p= image_tag p.image
          - else
            p The Lot has no image
      .panel-footer
        = link_to "Edit", edit_admin_lot_path(@lot), class: 'btn btn-primary'