config/routes.rb
Auction::Application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  root :to => "lots#index"
  get 'admin' => 'admin/categories#index'

  namespace :admin do
    resources :products, :categories, :lots
  end

  resources :lots, only: [:index, :show] do
    resources :bets, only: [:create]
  end

end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :category
  has_many :pictures, as: :imageable

  validates :name, :shop_price, :description, presence: true
  validates :name,
            uniqueness: true,
            length: { in: 3..50 }
  #validates :image, length: { in: 5..50 }
  validates :shop_price, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :description, length: { in: 5..1000 }

  accepts_nested_attributes_for :pictures, allow_destroy: true
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
    @categories = Category.all.map {|c| [c.name, c.id] }
    @product.pictures.build
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:success] = "Product created."
      redirect_to [:admin, @product]
    else
      render 'new'
    end
  end

  def edit
    @categories = Category.all.map {|c| [c.name, c.id] }
  end

  def update
    if @product.update_attributes(product_params)
      flash[:success] = "Product updated."
      redirect_to [:admin, @product]
    else
      render 'edit'
    end
  end

  def destroy
    @product.destroy
    flash[:success] = "Product deleted."
    redirect_to admin_products_url
  end

  private
    def product_params
      params.require(:product).permit(:name, :shop_price, :image, :description,
                                      :category_id, pictures_attributes: [:id, :image, :_destroy])
    end

    def set_product
      @product = Product.find(params[:id])
    end
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/_breadcrumbs.html.slim
ul.breadcrumb
  li
    = link_to "categories", admin_categories_path
    span.divider
  - for a in @product.category.ancestors
    li
      = link_to a.name, admin_category_path(a)
      span.divider
  li.active = @product.category.name

app/views/admin/products/_error_messages.html.slim
-if @product.errors.any?
    div id="error_explanation"
      div class="alert alert-error"
        |The form contains #{pluralize(@product.errors.count, "error")}.
      ul
        - @product.errors.full_messages.each do |msg|
            li = "*#{msg}"

app/views/admin/products/_form.html.slim
.row
  .col-lg-8
    .panel.panel-default
      .panel-heading
        .category_title
          - if @product.new_record?
            | Create new product
          - else
            = "Edit "+@product.name
      .panel-body
        = nested_form_for [:admin, @product], class:'form' do |f|
          .control-group
            = render 'error_messages'
          .control-group
            = f.label :name
            = f.text_field :name, class: 'form-control'
          .control-group
            = f.label :category_id
            = f.select :category_id, Category.all.map {|c| [c.name, c.id] }, {include_blank: 'None'}, class: 'form-control'
          .control-group
            = f.label :shop_price
            = f.text_field :shop_price, class: 'form-control'
          .control-group
            = f.label :description
            = f.text_area :description, size: '40x5'
          .control-group
            br
            = f.fields_for :pictures do |builder|
              = render "picture_block", f: builder
            = link_to_add_fields "Add a picture", f, :pictures

          .control-group
            - if @product.new_record?
              = f.submit "Create the product", class: "btn btn-large btn-primary"
            - else
              = f.submit "Edit the product", class: "btn btn-large btn-primary"
              | &nbsp
              = link_to "Show", admin_product_path(@product), class: 'btn btn-primary'

app/views/admin/products/_list.html.slim
.row
  .col-lg-12
    .panel.panel-default
      .panel-heading
        - if defined?(title_list)
          = title_list
      .panel-body
        .table-responsive
          table#dataTables.table.table-striped.table-bordered.table-hover
            thead
              tr
                th Id
                th Name
                th Shop Price
                th
                th
            tbody
              - for p in @products
                tr
                  td
                    = p.id
                  td
                    = link_to p.name, admin_product_path(p), class: 'product'
                  td
                    = p.shop_price.to_s
                  td.center
                    = link_to "Edit", edit_admin_product_path(p)
                  td.center
                    = link_to "Delete", admin_product_path(p), method: "delete", data: { confirm: "You sure?" }, class: 'delete_link'

app/views/admin/products/_picture.html.slim
.picture_block
  - if f.image
    p= image_tag f.image, width: '200'

app/views/admin/products/_picture_block.html.slim
.picture_block
  p= image_tag f.object.image, width: '200'
  = f.label :image
  = f.file_field :image
  = f.hidden_field :_destroy
  = link_to "Remove Image", "#",class: "remove_images"

app/views/admin/products/_right.html.slim
.col-lg-4
  .well.sidebar-nav
    p
      = link_to "Add Product", new_admin_product_path, class: "btn btn-small btn-primary"

    ul.nav.nav-list
      li.nav-header

    /= render 'jstree'

app/views/admin/products/edit.html.slim
= render 'form'

app/views/admin/products/index.html.slim
.list
  = render 'list', title_list: 'Products'

app/views/admin/products/new.html.slim
= render 'form'

app/views/admin/products/show.html.slim
= render 'breadcrumbs'
.row
  .col-lg-5
    .panel.panel-default
      .panel-heading
        .product_title
          = @product.name
      .panel-body
        - if @product.pictures
          - @product.pictures.each do |p|
            = render 'picture', f:p
        - else
          p The Product has no image
      .panel-footer
        = link_to "Edit", edit_admin_product_path(@product), class: 'btn btn-primary'