config/routes.rb
Auction::Application.routes.draw do
  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}

  root :to => "lots#index"
  get 'admin' => 'admin/categories#index'

  namespace :admin do
    resources :products, :categories, :lots
  end

  resources :lots, only: [:index, :show] do
    resources :bets, only: [:create]
  end

end

app/models/lot.rb
class Lot < ActiveRecord::Base

  belongs_to :product
  has_many :bets
  validates :product_id, :time_step, :bet_step, presence: true
  validates :time_step, numericality: { greater_than_or_equal_to: 30 }

  enum :status, [:not_started, :started, :finished], :allow_nil => true
  after_create :init_lot

  def name
    self.product.name
  end

  def description
    self.product.description
  end

  def category
    self.product.category
  end

  def pictures
    self.product.pictures
  end

  def active?
    if self.status == :started
      true
    else
      false
    end
  end

  def change_for_bet
    self.time_end += self.time_step
    self.current_price += self.bet_step
    self.save!
  end

  def last_bet_user
    if self.bets.count > 0 && self.bets.last.user_id
      User.find(self.bets.last.user_id)
    else
      nil
    end
  end

  private
    def init_time_start
      self.time_start = Time.now
    end

    def init_time_end
      self.time_end = self.time_start + self.time_step
    end

    def init_current_price
      self.current_price = self.start_price
    end

    def init_status
      self.status = :not_started
    end

    def init_lot
      init_time_start
      init_time_end
      init_current_price
      init_status
      self.save!
    end

end

app/controllers/admin/lots_controller.rb
class Admin::LotsController < Admin::BaseController
  before_action :set_lot, only: [:show, :edit, :update, :destroy]
  before_action :set_time_start, only: [:update] # temp

  def index
    @lots = Lot.all
  end

  def show
  end

  def new
    @lot = Lot.new
    @products = Product.all.map {|p| [p.name, p.id]}
  end

  def create
    @lot = Lot.new(lot_params)
    if @lot.save
      flash[:success] = "Lot created."
      redirect_to [:admin, @lot]
    else
      render 'new'
    end
  end

  def edit
    @products = Product.all.map {|p| [p.name, p.id]}
  end

  def update
    if @lot.update_attributes(lot_params)
      if is_starting? # temp
        @lot.time_end = @lot.time_start + @lot.time_step
        @lot.save
      end
      flash[:success] = "Lot updated."
      redirect_to [:admin, @lot]
    else
      render 'edit'
    end
  end

  def destroy
    @lot.destroy
    flash[:success] = "Lot deleted."
    redirect_to admin_lots_url
  end

  private
    def lot_params
      params.require(:lot).permit(:product_id, :time_step, :bet_step, :start_price, :status)
    end

    def set_lot
      @lot = Lot.find(params[:id])
    end

    def is_starting? #I don't like this idea
      prev_status = @lot.status
      current_status = params[:lot][:status]
      starting =  prev_status.to_s == 'not_started' && current_status == 'started'
      if starting
        return true
      else
        return false
      end
    end

    def set_time_start # temp
      @lot.time_start = Time.now if is_starting?
    end
end

app/controllers/lots_controller.rb
class LotsController < ApplicationController
  
  def index
   @lots= Lot.order('created_at DESC').page(params[:page])

  end

  def show
    @lot = Lot.find(params[:id])
  end

end

app/helpers/admin/lots_helper.rb
module Admin::LotsHelper
end

app/helpers/lots_helper.rb
module LotsHelper
end

app/views/lots/_thumbnail.html.slim
.row
  ul.hProductItems.clearfix
    - @lots.each do |l|
      li.span3.clearfix id='lot_#{l.id}'
        p
          = '#'+l.id.to_s
          | &nbsp
          = link_to l.name, lots_path(l)
        .thumbnail
          a href=""
            - if l.pictures.count > 0
              = image_tag l.pictures.first.image, width: 130
            - else
              = image_tag image_path('support/no_image.jpg'), width: 130
        .thumbSetting
          .thumbUser
            a.invarseColor href="#"
              p
                | User:
                span.user_bet
                  = l.last_bet_user.email unless l.last_bet_user.nil?
          .thumbTime
            - if l.time_end
              span.time_end
                = l.time_end.to_formatted_s(:db)
          .thumbButtons
            a.btn href='#{lot_path(l)}'
              i.icon-zoom-in
            | &nbsp
            = link_to 'Bet', lot_bets_path(lot_id: l.id), remote: true, class: 'btn btn-success', method: :post
            | &nbsp
            a.btn.btn-primary
              |$
              span.current_price
                = l.current_price

app/views/lots/_thumbnail2.html.slim
ul.thumbnails
  - @lots.each do |l|
    li.span4 id='lot_#{l.id}'
      .thumbnail
        p
          = '#'+l.id.to_s
          | &nbsp
          = link_to l.name, lots_path(l)
        a.image-container
          - if l.pictures.count > 0
            = image_tag l.pictures.first.image, width: 160
          - else
            = image_tag image_path('support/no_image.jpg'), width: 160
        .caption
          h5
            - if l.time_end
              span.time_end
                = l.time_end.to_formatted_s(:db)
          p
            | User:
            span.user_bet
              = l.last_bet_user.email unless l.last_bet_user.nil?
          h4
            a.btn href='#{lot_path(l)}'
              i.icon-zoom-in
            = link_to 'Bet', lot_bets_path(lot_id: l.id), remote: true, class: 'btn btn-success', method: :post
            /a.btn.btn-success
              |Bet

            a.btn.btn-primary
              |$
              span.current_price
                = l.current_price

app/views/lots/index.html.slim
.row
  .span12
    #featuredItems
      .titleHeader.clearfix
        h3
          | Featured Items
        .pagers
          .btn-toolbar
            button.btn.btn-mini
              | View All
      = render 'thumbnail'
= paginate @lots
= subscribe_to "/lots/update"

app/views/lots/show.html.slim
.row
  .span12
    = render 'shared/breadcrumb'
    .row id="lot_#{@lot.id}"
      .span4
        .fotorama data-nav="thumbs"
          - if true#@lot.product.pictures.size>0
            - @lot.pictures.each do |p|
              a href="#{p.image}"
                = image_tag p.image, width: '50%'
      .span5
        #pb-left-column
          h3.lot_name
            = @lot.name
          #short_description_block
            #short_description_content
              p.lot_description
                = @lot.description
                /| Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed at ante. Mauris eleifend, quam a vulputate dictum, massa quam dapibus leo, eget vulputate orci purus ut lorem. In fringilla mi in ligula.
          hr
          #product_attributes
            p
              | Disk space :
              | Color :
              | Availability:
              | Ecomomy :
          hr
          p
            h4
              | Time end:
              - if @lot.time_end
                strong
                  span.time_end
                    = @lot.time_end.to_formatted_s(:db)
          p
            h4.price
              strong
                |$
                span.current_price
                  = @lot.current_price
          p
            h4
              | User:
              strong
                span.user_bet
                  = @lot.last_bet_user.email unless @lot.last_bet_user.nil?
          p
            = link_to 'Bet', lot_bets_path(lot_id: @lot.id), remote: true, method: :post, class: 'btn btn-success'

= subscribe_to "/lots/update"

app/views/lots/show_old.html.slim
.span12
  #gallery.span6
    a href="#" title="Fujifilm FinePix S2950 Digital Camera"
        img alt="Fujifilm FinePix S2950 Digital Camera" src="#{@lot.pictures.first.image}" style="width:100%"

    #differentview.moreOptopm.carousel.slide
      .carousel-inner
        .item.active
          - if @lot.pictures.size>0
            - @lot.pictures do |p|
              a href="#{p.image}"
                /img alt="" src="#{p.image}" style="width:29%"
                image_tag image_path('support/no_image.jpg'), width: '29%'
          - if true
            a href="#{image_path('support/no_image.jpg')}"
              = image_tag image_path('support/no_image.jpg'), width: '29%'
              /img alt="" src="#{image_path('support/no_image.jpg')}" style="width:29%"
            a href="#{image_path('support/no_image.jpg')}"
              = image_tag image_path('support/no_image.jpg'), width: '29%'
            a href="#{image_path('support/no_image.jpg')}"
              = image_tag image_path('support/no_image.jpg'), width: '29%'
              /img alt="" src="#{image_path('support/no_image.jpg')}" style="width:29%"
        .item
          a href="#{image_path('support/no_image.jpg')}"
            = image_tag image_path('support/no_image.jpg'), width: '29%'
            /img alt="" src="#{image_path('support/no_image.jpg')}" style="width:29%"
          a href="#{image_path('support/no_image.jpg')}"
            = image_tag image_path('support/no_image.jpg'), width: '29%'
          a href="#{image_path('support/no_image.jpg')}"
            = image_tag image_path('support/no_image.jpg'), width: '29%'
            /img alt="" src="#{image_path('support/no_image.jpg')}" style="width:29%"
    .btn-toolbar
      .btn-group
        span.btn
          i.icon-envelope
        span.btn
          i.icon-print
        span.btn
          i.icon-zoom-in
        span.btn
          i.icon-star
        span.btn
          i.icon-thumbs-up
        span.btn
          i.icon-thumbs-down
  .span4 id="lot_#{@lot.id}"
    h3
      = @lot.name
    h4
      | Time end:
      - if @lot.time_end
        span.time_end
          = @lot.time_end.to_formatted_s(:db)
    small - (14MP, 18x Optical Zoom) 3-inch LCD
    hr.soft
      form.form-horizontal.qtyFrm
        .control-group
          label.control-label
            |$
            span.current_price
              = @lot.current_price
          label
            | User:
            span.user_bet
              = @lot.last_bet_user.email unless @lot.last_bet_user.nil?
          /.controls
            input.span12 placeholder="Qty." type="number"
          br
            = link_to 'Bet', lot_bets_path(lot_id: @lot.id), remote: true, method: :post, class: 'btn btn-success btn-large'
            /button.btn.btn-large.btn-primary.pull-right type="submit"
              | Add to cart
              i.icon-shopping-cart
      hr.soft
        h4 100 items in stock
        form.form-horizontal.qtyFrm.pull-right
          .control-group
            label.control-label
              span Color
            .controls
              select.span12 style="visibility: visible;"
                option Black
                option Red
                option Blue
                option Brown
        hr.soft.clr
          p
            | 14 Megapixels. 18.0 x Optical Zoom. 3.0-inch LCD Screen. Full HD photos and 1280 x 720p HD movie capture. ISO sensitivity ISO6400 at reduced resolution.
            | Tracking Auto Focus. Motion Panorama Mode. Face Detection technology with Blink detection and Smile and shoot mode. 4 x AA batteries not included. WxDxH 110.2 ×81.4x73.4mm.
            | Weight 0.341kg (excluding battery and memory card). Weight 0.437kg (including battery and memory card).
          a.btn.btn-small.pull-right href="#detail"
            | More Details
          br.clr
            a href="#" name="detail"
            hr.soft

= subscribe_to "/lots/update"